package com.cjs.qa.bts;

import com.cjs.qa.bts.pages.AddNewAddressClientPage;
import com.cjs.qa.bts.pages.AddNewPolicyPage;
import com.cjs.qa.bts.pages.AddNewProductPage;
import com.cjs.qa.bts.pages.AdminFunctionsPage;
import com.cjs.qa.bts.pages.BI_AdvantagePage;
import com.cjs.qa.bts.pages.BI_AgencyInformationPage;
import com.cjs.qa.bts.pages.BI_BasicInfoPage;
import com.cjs.qa.bts.pages.BI_BillingInformationPage;
import com.cjs.qa.bts.pages.BI_BillingPage;
import com.cjs.qa.bts.pages.BI_ButtonsPage;
import com.cjs.qa.bts.pages.BI_LeftNav;
import com.cjs.qa.bts.pages.BI_MiscellaneousInformationPage;
import com.cjs.qa.bts.pages.BI_RightNav;
import com.cjs.qa.bts.pages.BI_TerrorismPage;
import com.cjs.qa.bts.pages.BI_UnderwritingPage;
import com.cjs.qa.bts.pages.CPLResultsPage;
import com.cjs.qa.bts.pages.CopyPolicyPage;
import com.cjs.qa.bts.pages.IssuePage;
import com.cjs.qa.bts.pages.IssuePageLeftNav;
import com.cjs.qa.bts.pages.LoginPage;
import com.cjs.qa.bts.pages.ManageProductsPage;
import com.cjs.qa.bts.pages.ManageProductsRightNav;
import com.cjs.qa.bts.pages.NamedInsuredsPage;
import com.cjs.qa.bts.pages.PolicyIssuancePage;
import com.cjs.qa.bts.pages.PremiumSummaryPage;
import com.cjs.qa.bts.pages.PremiumSummaryRightNav;
import com.cjs.qa.bts.pages.RateLeftNavPage;
import com.cjs.qa.bts.pages.RatePage;
import com.cjs.qa.bts.pages.RateRightNav;
import com.cjs.qa.bts.pages.ReferenceMaterialsPage;
import com.cjs.qa.bts.pages.RequestPrintPage;
import com.cjs.qa.bts.pages.RequestPrintRightNav;
import com.cjs.qa.bts.pages.SearchPage;
import com.cjs.qa.bts.pages.SearchResultsPage;
import com.cjs.qa.bts.pages.SearchRightNav;
import com.cjs.qa.bts.pages.SidbarAdminFunctionsPage;
import com.cjs.qa.bts.pages.SidbarReferenceMaterialsPage;
import com.cjs.qa.bts.pages.Sidebar;
import com.cjs.qa.bts.pages._BTSCrosswordChallengePage;
import com.cjs.qa.core.Environment;
import com.cjs.qa.utilities.SoftAssert;
import org.openqa.selenium.WebDriver;

public class BTS {
  public SoftAssert SoftAssert;
  public _BTSCrosswordChallengePage _BTSCrosswordChallengePage;
  public AddNewAddressClientPage AddNewAddressClientPage;
  public AddNewPolicyPage AddNewPolicyPage;
  public AddNewProductPage AddNewProductPage;
  public AdminFunctionsPage AdminFunctionsPage;
  public BI_AdvantagePage BI_AdvantagePage;
  public BI_AgencyInformationPage BI_AgencyInformationPage;
  public BI_BasicInfoPage BI_BasicInfoPage;
  public BI_BillingInformationPage BI_BillingInformationPage;
  public BI_BillingPage BI_BillingPage;
  public BI_ButtonsPage BI_ButtonsPage;
  public BI_LeftNav BI_LeftNav;
  public BI_MiscellaneousInformationPage BI_MiscellaneousInformationPage;
  public BI_RightNav BI_RightNav;
  public BI_TerrorismPage BI_TerrorismPage;
  public BI_UnderwritingPage BI_UnderwritingPage;
  public CopyPolicyPage CopyPolicyPage;
  public CPLResultsPage CPLResultsPage;
  public IssuePage IssuePage;
  public IssuePageLeftNav IssuePageLeftNav;
  public LoginPage LoginPage;
  public ManageProductsPage ManageProductsPage;
  public ManageProductsRightNav ManageProductsRightNav;
  public NamedInsuredsPage NamedInsuredsPage;
  public PolicyIssuancePage PolicyIssuancePage;
  public PremiumSummaryPage PremiumSummaryPage;
  public PremiumSummaryRightNav PremiumSummaryRightNav;
  public RatePage RatePage;
  public RateLeftNavPage RateLeftNavPage;
  public RateRightNav RateRightNav;
  public ReferenceMaterialsPage ReferenceMaterialsPage;
  public RequestPrintPage RequestPrintPage;
  public RequestPrintRightNav RequestPrintRightNav;
  public SearchPage SearchPage;
  public SearchResultsPage SearchResultsPage;
  public SearchRightNav SearchRightNav;
  public Sidebar Sidebar;
  public SidbarAdminFunctionsPage SidbarAdminFunctionsPage;
  public SidbarReferenceMaterialsPage SidbarReferenceMaterialsPage;

  public BTS(WebDriver webDriver) {
    SoftAssert = new SoftAssert();
    _BTSCrosswordChallengePage = new _BTSCrosswordChallengePage(webDriver);
    AddNewAddressClientPage = new AddNewAddressClientPage(webDriver);
    AddNewPolicyPage = new AddNewPolicyPage(webDriver);
    AddNewProductPage = new AddNewProductPage(webDriver);
    AdminFunctionsPage = new AdminFunctionsPage(webDriver);
    BI_AdvantagePage = new BI_AdvantagePage(webDriver);
    BI_AgencyInformationPage = new BI_AgencyInformationPage(webDriver);
    BI_BasicInfoPage = new BI_BasicInfoPage(webDriver);
    BI_BillingInformationPage = new BI_BillingInformationPage(webDriver);
    BI_BillingPage = new BI_BillingPage(webDriver);
    BI_ButtonsPage = new BI_ButtonsPage(webDriver);
    BI_LeftNav = new BI_LeftNav(webDriver);
    BI_MiscellaneousInformationPage = new BI_MiscellaneousInformationPage(webDriver);
    BI_RightNav = new BI_RightNav(webDriver);
    BI_TerrorismPage = new BI_TerrorismPage(webDriver);
    BI_UnderwritingPage = new BI_UnderwritingPage(webDriver);
    CopyPolicyPage = new CopyPolicyPage(webDriver);
    CPLResultsPage = new CPLResultsPage(webDriver);
    IssuePage = new IssuePage(webDriver);
    IssuePageLeftNav = new IssuePageLeftNav(webDriver);
    LoginPage = new LoginPage(webDriver);
    ManageProductsPage = new ManageProductsPage(webDriver);
    ManageProductsRightNav = new ManageProductsRightNav(webDriver);
    NamedInsuredsPage = new NamedInsuredsPage(webDriver);
    PolicyIssuancePage = new PolicyIssuancePage(webDriver);
    PremiumSummaryPage = new PremiumSummaryPage(webDriver);
    PremiumSummaryRightNav = new PremiumSummaryRightNav(webDriver);
    RatePage = new RatePage(webDriver);
    RateLeftNavPage = new RateLeftNavPage(webDriver);
    RateRightNav = new RateRightNav(webDriver);
    ReferenceMaterialsPage = new ReferenceMaterialsPage(webDriver);
    RequestPrintPage = new RequestPrintPage(webDriver);
    RequestPrintRightNav = new RequestPrintRightNav(webDriver);
    SearchPage = new SearchPage(webDriver);
    SearchResultsPage = new SearchResultsPage(webDriver);
    SearchRightNav = new SearchRightNav(webDriver);
    Sidebar = new Sidebar(webDriver);
    SidbarAdminFunctionsPage = new SidbarAdminFunctionsPage(webDriver);
    SidbarReferenceMaterialsPage = new SidbarReferenceMaterialsPage(webDriver);
    webDriver
        .manage()
        .timeouts()
        .pageLoadTimeout(java.time.Duration.ofSeconds(Environment.getTimeOutPage()));
  }
}
