@Vivit
Feature: Vivit Features

  Background: Environment Setup
    Given Environment Setup Vivit
      | Browser     | Chrome |
      | Environment | Tst    |
      | Company     | Vivit  |
      | LOB         | App    |

  Scenario: Scenario_01
  Given pGiven "Scenario_01"
  When pWhen
  And pAnd
  But pBut
  Then pThen

  @VivitBoard
  Scenario Outline: Board Members
    Given Board of Directors Page <Scenario Name> "http://www.vivit-worldwide.org/page/2018board"
    Then Board Member <Name> Exists <Title>, <Email>, <Company>, <Address>, <Country>, <Duties>

    Examples: Board Members
      | Scenario Name                               | Name                     | Title                                       | Email                                     | Company                       | Address                     | Country          | Duties                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | "President"                                 | "Richard Bishop"         | "President"                                 | "richard.bishop@vivit-worldwide.org"      | "Trust IV"                    | "Manchester"                | "United Kingdom" | "The President of Vivit has primary responsibility for managing Vivit for the benefit of our membership and the wider Micro Focus software user community. As well as setting direction and providing support for fellow board members and staff, the President attends staff and board meetings on a regular basis and acts as a contact point for Micro Focus when they wish to engage with the user community. The President holds fiduciary responsibility for Vivit and acts to ensure that the organisation remains financially stable and acts in the best interest of its members."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | "Vice President of Operations"              | "Mark Herbert"           | "Vice President of Operations"              | "mark.herbert@vivit-worldwide.org"        | "Dignity Health"              | "Phoenix, Arizona "         | "United States"  | "The Vivit Vice President of Operations assists and supports the Vivit President in running the Vivit organization from an operational perspective. Responsibilities include working with the Vivit President and Executive Officers to review issues that require a Presidential and/or Executive decision and offer feedback as part of that process, standing in for the President as needed and requested, and participating in weekly meetings with the Vivit contractors to review their progress with various tasks and offer guidance when they have questions and/or need direction."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | "Vice President of Strategy and Innovation" | "Todd DeCapua"           | "Vice President of Strategy and Innovation" | "todd.decapua@vivit-worldwide.org"        | "Corporation Service Company" | "Wilmington, Delaware "     | "United States"  | "The Vice President of Strategy and Innovation assists and supports the President in running the Vivit Worldwide organization. Responsibilities include working with the President and Executive Officers to review issues that require a Presidential and/or Executive decision and offer feedback as part of that process, standing in for the President as needed and requested. The Vice President of Strategy and Innovation will also facilitate and review future directions across the board, and collaboration with other key external decision makers, so to deliver on the future of Vivit Worldwide with the Board of Directors."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | "Treasurer"                                 | "Christopher J. Scharer" | "Treasurer"                                 | "christopher.scharer@vivit-worldwide.org" | "CJS Consulting, L.L.C."      | "West Des Moines, Iowa"     | "United States"  | "The treasurer (see section 5.0.4 of the Vivit bi-laws document) shall serve as chief financial officer of Vivit and will be responsible for all monies received and expended for the use of Vivit, shall cause Vivit to satisfy its financial obligations; develop financial plans and budgets; provide regular financial reports; provide for proper insurance coverage; manage Vivit investments; cause the annual corporate financial audit or review to occur, and shall serve as otherwise directed by the Board of Directors. Other responsibilities currently as directed by the Board of Directors include but are not limited to the following; periodically the treasurer has the responsibility of reporting Vivit finances (monthly/quarterly), ensuring board and staff members have a copy of the Vivit expense policy and the required expense forms for that particular year, reviewing and approving budgets for conferences and any other activities that require financial funding and reviewing and approving expense reports following the expense reimbursement policy. Finally, the treasurer ensures the accounting firm is retaining a copy of the receipts and the treasurers’ approvals." |
      | "Secretary"                                 | "Karen E. Semonson"      | "Secretary"                                 | "karen.semonson@vivit-worldwide.org"      | "Smart Solutions Inc."        | "Madison, Wisconsin"        | "United States"  | "The secretary shall be the recording secretary of all meetings of the Board of Directors and meetings of members; shall cause all notices required to be given by Vivit to be duly given and served; shall serve as parliamentarian of the corporation; cause the reports, statements and other documents required by law to be properly kept and filed; provide membership records; and maintain liaison with the Vivit attorney, and shall serve as otherwise directed by the Board of Directors."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | "Advocacy Chairperson"                      | "Tammy Young"            | "Advocacy Chairperson"                      | "tammy.young@vivit-worldwide.org"         | "Aflac Worldwide "            | "Columbus, Georgia"         | "United States"  | "The Advocacy Chairperson provides strategic oversight of Vivit’s external relations activities. The Director is the individual responsible for driving Vivit’s advocacy objectives. In consultation with the Vivit Board and staff, the Advocacy Chairperson executes the advocacy agenda by building and managing relationships with key external stakeholders (e.g. SIGs and LUGs, partners, Micro Focus)."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | "Community Chairperson"                     | "Mark Ford"              | "Community Chairperson"                     | "mark.ford@vivit-worldwide.org"           | "TIAA-CREF"                   | "Charlotte, North Carolina" | "United States"  | "The Community Chairperson communicates direction and priorities to the LUG and SIG leaders and solicits their feedback, needs and concerns to bring back to the board. The director works closely with Vivit LUG/SIG liaisons to make sure they have what they need to keep the LUGs and SIGs running smoothly so they can provide a valuable experience to the membership. The Community Chairperson also works on initiatives to grow Vivit’s membership and improves the overall level of engagement, soliciting input from LUG/SIG leaders at quarterly leader meetings. Finally, the Community Chairperson is responsible for providing updates pertaining to the following Vivit platforms; membership, webinar, mobile and reporting."                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | "Education Chairperson"                     | "Chris Trimper"          | "Education Chairperson"                     | "chris.trimper@vivit-worldwide.org"       | "Independent Health"          | "Willliamsville, New York"  | "United States"  | "The Education Chairperson will help facilitate training and education for the Vivit Community. The director will act as a liaison between Micro Focus and various subject matter experts to bring the highest quality teaching to our members. The director will assist the Vivit team in seeking out relevant speakers and moderators for webinars and regional and global conferences when Vivit hosts speaking tracks. The Education Chairperson will work closely with both the Community and Advocacy Directors so the Vivit Community continues to have the greatest level of service and support."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | "Special Projects Co-Chairperson"           | "Alvin Sumter"           | "Special Projects Co-Chairperson"           | "alvin.sumter@vivit-worldwide.org"        | "Thyssenkrupp Elevator"       | "Atlanta, Georgia"          | "United States"  | "The Special Projects Chairperson holds a vital role, particularly whilst Vivit undergoes a period of transition during the merger of HPE Software and Micro Focus. As well as assisting the Community, Education and Advocacy Chairpersons in their initiatives, this chairperson is responsible for managing other Vivit projects such as ensuring GDPR compliance. Like all directors, the special projects chairperson shares responsibility for the day-to-day running of the user group for the benefit of our membership."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | "Special Projects Co-Chairperson"           | "Bernard Szymczak"       | "Special Projects Co-Chairperson"           | "bernard.szymczak@vivit-worldwide.org"    | "Progressive Insurance"       | "Mayfield, Ohio"            | "United States"  | "The Special Projects Chairperson holds a vital role, particularly whilst Vivit undergoes a period of transition during the merger of HPE Software and Micro Focus. As well as assisting the Community, Education and Advocacy Chairpersons in their initiatives, this chairperson is responsible for managing other Vivit projects such as ensuring GDPR compliance. Like all directors, the special projects chairperson shares responsibility for the day-to-day running of the user group for the benefit of our membership."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

  @VivitStaff
  Scenario Outline: Staff Members
    Given Staff Page <Scenario Name> "http://www.vivit-worldwide.org/staff/"
    Then Staff Member <NameTitle> Exists <eMail>, <Phone>

    Examples: Staff Members
      | Scenario Name                           | NameTitle                                              | eMail                                   | Phone                |
      | "Vivit Engagement Director"             | "Stephanie Konkoy - Vivit Engagement Director"         | "stephanie.konkoy@vivit-worldwide.org"  | "+1 317 344 0284"    |
      | "Sponsorship Liaison"                   | "Rocky Pisto - Sponsorship Liaison"                    | "rocky.pisto@vivit-worldwide.org"       | "+1 614 408 8500"    |
      | "Vivit Global Assistant"                | "Rhonda Quaranta - Vivit Global Assistant"             | "rhonda.quaranta@vivit-worldwide.org"   | "949-302-1776"       |
      | "Global Marketing and Services Liaison" | "Susan Russel - Global Marketing and Services Liaison" | "susan.russel@vivit-worldwide.org"      | ""                   |
      | "Website Community Administrator"       | "Julanne Rutten - Website Community Administrator"     | "jlrcreativeservices@outlook.com"       | ""                   |
      | "Global Engagement Coordinator"         | "Teri Sarallo - Global Engagement Coordinator"         | "teri.sarallo@vivit-worldwide.org"      | "-222"               |
      | "Marketing Director"                    | "Jill Stefan - Marketing Director"                     | "jill.stefan@vivit-worldwide.org"       | "+1 708 275 7042"    |
      | "EMEA/APJ Liaison"                      | "Annemarie Stuiver - EMEA/APJ Liaison"                 | "annemarie.stuiver@vivit-worldwide.org" | "+31 (0)642 911 385" |